USE app_users;
CREATE TABLE `tweets` (
`id` INT(11) NOT NULL AUTO_INCREMENT, 
`user_id` INT(11) NOT NULL,
`tweets` VARCHAR(300) NOT NULL,
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) 
); 